services:
  - type: web
    name: glamstar-user
    env: node
    rootDir: .
    buildCommand: "npm install && npm run build"
    startCommand: "npx serve -s build"
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
